[package]
name = "relnotes"
version = "0.1.0"
authors = ["Erin Power <xampprocky@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
chrono = "0.4"
serde = "1"
serde_json = "1"
askama = { version = "0.11", default-features = false }
